node() {
  withMaven(maven:'M3') {
    stage('Checkout') {
      git url: 'https://github.com/Tass21/sample-spring-microservices-new.git', credentialsId: 'Tass21', branch: 'develop'
    }
    stage('Build') {
      dir('config-service') {
        sh 'mvn clean install'
        def pom = readMavenPom file:'pom.xml'
        print pom.version
        env.version = pom.version
        currentBuild.description = "Release: ${env.version}"
      }
    }
    stage('Image') {
    }
  }
}